# Merged data GS location
merged_data:
  sheet_id: 1ZpIbeSmXTZ41GLUeLmUAok_uajqlDpWMPr59KFfBVBc
  sheet_name: shootings_data_merged

# GOOGLE SHEET IDENTIFIERS
google_sheets:
  northeast:
    sheet_id: 1quuwKITarVyTwp3wfIsx37Rebsv0z6mfuB7Mw7aqH1g
    sheet_name: Research!
    cols_row: 1
    data_start: 3
    col_mappings:
      State: state
      Date: date
      Victims Name: victim_name
      Officer Name: officer_name
      Victim Armed/Unarmed: armed_unarmed
      Cause of Death: cause_of_death
      Officer Charged: officer_charged
      Alleged Crime: alleged_crime
      County: county
      Link_1: link_1
      Link_2: link_2
      Summary: summary
  southeast:
    sheet_id: 1h-hbkHB6Fw80eHZPCaElKIbtCzqL4YrmDY8ye-t-WAA
    sheet_name: Research!
    cols_row: 2
    data_start: 3
    col_mappings: 
      State: state
      Date: date
      Victims Name: victim_name
      Officer Name: officer_name
      Victim Armed/Unarmed: armed_unarmed
      Cause of Death: cause_of_death
      Was Officer Charged?: officer_charged
      Reason for Incident: alleged_crime
      County: county
      Link_1: link_1
      Summary: summary
  north_central:
    sheet_id: 1bmbT4i2TWepTMKLvpI-5s_zORqVzZQEcD5mfUFq9dXI
    sheet_name: "North Central: MT,WY, CO,KS, NE, ND, SD"
    cols_row: 1
    data_start: 3
    col_mappings:
      State: state
      Date: date
      Victims Name: victim_name
      Officer Name: officer_name
      Victim Armed/Unarmed: armed_unarmed
      Cause of Death: cause_of_death
      Officer Charged: officer_charged
      Alleged Crime: alleged_crime
      County: county
      Link_1: link_1
      Link_2: link_2
      Summary: summary
  central: 
    sheet_id: 1dBcuQ5EI68MsVc7AkedeLfzIRt6y31Vgnp1B2bp1Qa4
    sheet_name: "Central: IA, MN, MI, IL, MO, IN, OH, WI"
    cols_row: 2
    data_start: 3
    col_mappings:
      State: state
      Date: date
      Victims Name: victim_name
      Officer Name: officer_name
      Victim Armed/Unarmed: armed_unarmed
      Cause of Death: cause_of_death
      Officer Charged: officer_charged
      Alleged Crime: alleged_crime
      County: county
      Link_1: link_1
      Link_2: link_2
      Summary: summary
  south_central: 
    sheet_id: 1pLtcqqHQyS05JToryAF8EApxb6g4SL-C-nLisPdOpqg
    sheet_name: "South Central: TX, NM, OK, LA"
    cols_row: 1
    data_start: 2
    col_mappings:
      State: state
      Date: date
      Victims Name: victim_name
      Officer Name: officer_name
      Office Charged (Y/N): officer_charged
      Victim Armed (Y/N): armed_unarmed
      Cause of death: cause_of_death
      Alleged Crime: alleged_crime
      County: county
      Link_1: link_1
      Summary: summary
  northwest: 
    sheet_id: 1NxNZ2hYkkz7JP1UIZMmMQU-1AGovPdRTE3PQttWapHE
    sheet_name: "Northwest- WA, OR, ID, AK, HI"
    cols_row: 1
    data_start: 3
    col_mappings:
      State: state
      Date: date
      Victims Name: victim_name
      Officer Name: officer_name
      Officer Charged (As of now): officer_charged
      Victim Armed/Unarmed: armed_unarmed
      Cause of Death: cause_of_death
      Alleged Crime: alleged_crime
      County: county
      Link 1: link_1
      Link 2: link_2
      Link 3: link_3
      Link 4: link_4
      Summary: summary
  southwest: 
    sheet_id: 15lzxwVnkS-UjTWf3OCtSVNfy4ol5k-ToZkeKKOHGbqY
    sheet_name: "Southwest: CA, NV, AZ, UT"
    cols_row: 2
    data_start: 3
    col_mappings:
      State: state
      Date: date
      Victims Name: victim_name
      Officer Name: officer_name
      Victim Armed/Unarmed: armed_unarmed
      Cause of Death: cause_of_death
      Officer Charged: officer_charged
      Summary: summary
      Alleged Crime: alleged_crime
      County: county
      Link_1: link_1
      Link_2: link_2
